name: Deploy CEJST Preview
on:
  pull_request:
    branches:
      - main
      - "**/release/**"
    paths:
      - "client/**/*"
env:
  PR_NUMBER: ${{github.event.pull_request.number}}
  WORKING_DIRECTORY: ./client
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Setup and Environment
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set DESTINATION_FOLDER for branch
        run: |
          echo "DESTINATION_FOLDER=$(echo $PR_NUMBER-$GITHUB_SHA | cut -c 1-11)" >> $GITHUB_ENV
      - name: Set COMMIT_HASH for branch
        run: |
          echo "COMMIT_HASH=$(echo $GITHUB_SHA)" >> $GITHUB_ENV

      # Build and Test
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present
        env:
          # See the client readme for more info on environment variables:
          # https://github.com/usds/justice40-tool/blob/main/client/README.md
          DATA_SOURCE: cdn
          # SITE_URL: "${{ secrets.STAGE_SITE_URL }}"
          PATH_PREFIX: "/pr-${{env.DESTINATION_FOLDER}}"
          # MAPBOX_STYLES_READ_TOKEN: "${{ secrets.MAPBOX_STYLES_READ_TOKEN }}"
      - name: Get directory contents
        run: ls -la public
      - name: Lint
        run: npm run lint
        # Disabling for now due to jsonlint - TODO: put this back
      # - name: License Check
      #   run: npm run licenses
      - name: Test
        run: npm test

      # Deploy to AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PREVIEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREVIEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Deploy to S3
        run: aws s3 sync ./public/ s3://cejst-2-test/pr-${{env.DESTINATION_FOLDER}}/ --delete
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PREVIEW_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/pr-${{env.DESTINATION_FOLDER}}/*"

      # Notify PR
      - name: Update PR with deployed URL
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            **🚢  Here is the preview deployment link: 🚢**   
            Find it here: https://d1ut1n0e9o10r.cloudfront.net/pr-${{env.DESTINATION_FOLDER}}/ !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          allow-repeats: false
